### PR TITLE
[KAN-5]:home-fourth-section

### PR DESCRIPTION
**Pull request by keziabaidoo**
In this pull request, I have finished the home-fourth-section page, ensuring it matches the design across mobile, tablet, and desktop.

**What I worked on**

-Imported Button feature. 
- Mobile responsive active across all platforms.

### CODE REVIEW

**Review by poulami-saha — DISMISSED** [review]
With minor adjustments made, it looks good to me

**Review by FevenSeyfu — CHANGES_REQUESTED** [review]
Hi @keziabaidoo , I just noticed on the desktop your text overlap with the illustration image , I would suggest adding a second breaking point for media query with min-width: 960px as per previous suggestion

image

**Comment by keziabaidoo** [comment]
Thank you @FevenSeyfu,  I also just noticed that.

**Review by joanwolk — DISMISSED** [review]
This works! 👍 

There are some things I will refactor in a separate PR to show how the code can be simpler and smoother, but I'm going to merge this now. 🙂

**Comment by joanwolk** [comment]
Ahhh, I started poking around with a revision to the decorative image and forgot that it needs fixing before the merge. Thanks, @FevenSeyfu!

**Review by FevenSeyfu — APPROVED** [review]
with the current changes the overlapping problem has been resolved and everything else works fine . I think it is ready to be merged.

**Pull request merged**
